export const PLY_COPY = {
  welcomeTagline: 'Tu torneo está en juego',
  welcomeSub:
    'Consulta tu grupo, resultados y próximos partidos',
  yourGroup: 'Tu grupo',
  groupRivals: 'Rivales del grupo',
  youBadge: 'Tú',
  upcomingTitle: 'Tus próximos partidos',
  upcomingSub: 'Aún por jugar',
  noUpcoming: 'No tienes partidos pendientes',
  allGroupDone: 'Ya completaste todos tus partidos de grupo',
  scheduleTbd: 'Pendiente por programar',
  resultsTitle: 'Tus resultados',
  resultsSub: 'Partidos jugados',
  noResults: 'Aún no registras resultados',
  standingTitle: 'Tu posición actual',
  groupPreviewTitle: 'Resumen del grupo',
  groupPreviewSub: 'Posición, nombre y puntos',
  ctaFullGroup: 'Ver grupo completo',
  ctaMatrix: 'Ver cuadro de resultados',
  ctaRanking: 'Consultar ranking',
  progressLabel: 'Progreso en el grupo',
  nextRival: 'Tu próximo rival',
  insightsTitle: 'Lectura rápida',
  notInGroup: 'Aún no has sido asignado a un grupo',
  notInGroupHelp: 'Cuando la organización te asigne, verás rivales, partidos y ranking aquí.',
  loading: 'Cargando tu panel…',
  errorLoad: 'No pudimos cargar tu información. Intenta de nuevo.',
  noTournamentTitle: 'Aún no hay torneos visibles',
  noTournamentBody:
    'No encontramos un torneo activo o no tienes acceso. Si acabas de unirte, pide a la organización que active el torneo o que te inscriba.',
  noGroupTitle: 'Aún no estás en un grupo de juego',
  noGroupBody:
    'Cuando te asignen a un grupo, aquí verás rivales, partidos, resultados y tu posición. Mientras tanto puedes revisar el listado de torneos.',
  ctaTournaments: 'Ver torneos',
  win: 'Ganaste',
  loss: 'Perdiste',
  winDefault: 'Victoria por default',
  lossDefault: 'Derrota por default',
} as const
